### ISSUE TITLE
Does the driver support Gemini Lake?

### ISSUE THREAD

**Issue by dmitryermilov** [intel/media-driver#376] opened 2018-10-23 11:41 UTC

**Comment by XinfengZhang** [comment] 2019-08-29 08:41
not yet. the device ID should already added, but not fully test.

**Comment by zcwang** [comment] 2020-04-06 15:20
Hi All,
Does intel-media-19.4.0 (or the latest upstream of media-driver) support GLK in Linux?
https://github.com/intel/media-driver/releases/tag/intel-media-19.4.0r

Thanks!
Gary

**Comment by zcwang** [comment] 2020-04-06 15:23
[GST-error-in-GLK_gary0406.log](https://github.com/intel/media-driver/files/4439260/GST-error-in-GLK_gary0406.log)
Error caused by GST plug-in vaapi in GLK/Ubuntu 18.04

"gst-launch-1.0 -ev videotestsrc num-buffers=600 ! video/x-raw,width=3840,height=2160,framerate=30/1 ! vaapih264enc ! h264parse ! mp4mux ! filesink location=test.mp4"

**Comment by zcwang** [comment] 2020-04-07 07:57
Related issue for reference
https://github.com/intel/media-driver/issues/897

**Comment by THX723** [comment] 2020-07-13 00:35
@XinfengZhang @dmitryermilov Curious if a timeline has been established for when GLK will be fully integrated and tested in the media driver?

**Comment by XinfengZhang** [comment] 2020-07-16 08:24
#1005 should fixed some issue with GLK

**Comment by XinfengZhang** [comment] 2020-10-19 12:48
@zcwang hi Gary, have you tried PR #1005 ?

**Comment by Jexu** [comment] 2022-12-02 05:30
As mentiosned above, this issue should have been fixed. So i will close this issue and feel free to re-open it agsin if you have any other questions. Thanks

**Closed by Jexu** 2022-12-02 05:30 UTC
Labels: Question/Discussion, P2
