### ISSUE TITLE
[Bug]: C++ One Definition Rule violation

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/media-driver#1452] opened 2022-07-01 12:30 UTC
### Which component impacted?

Build

### What happened?

When building with LTO enabled, they are some warning:
```
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:30: warning: type ‘struct KernelHeader’ violates the C++ One Definition Rule [-Wodr]
   30 | struct KernelHeader
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp:39: note: a different type is defined in another translation unit
   39 | struct KernelHeader {
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:32: note: the first difference of corresponding definitions is field ‘m_kernelCount’
   32 |     uint32_t m_kernelCount;
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp:40: note: a field of same name but different type is defined in another translation unit
   40 |     int m_kernelCount;
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:30: note: type ‘uint32_t’ should match type ‘int’
   30 | struct KernelHeader
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:568: warning: type ‘struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS’ violates the C++ One Definition Rule [-Wodr]
  568 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_common.h:32: note: a different type is defined in another translation unit
   32 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:570: note: the first difference of corresponding definitions is field ‘pSurfInput’
  570 |     PVPHAL_SURFACE                  pSurfInput;
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_common.h:34: note: a field of same name but different type is defined in another translation unit
   34 |     PVP_SURFACE                     pSurfInput;
      | 
/build/intel-media-driver/src/media-driver-intel-media-22.4.4/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:568: note: type ‘struct VPHAL_SURFACE *’ should match type ‘struct VP_SURFACE *’
  568 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
      | 
```

### What's the usage scenario when you are seeing the problem?

Others

### Debug Information

This is on 22.4.4, it might have been present before but I did not check.

**Comment by VickyZengg** [comment] 2023-02-03 05:55
Hi ArchangeGabriel, I can't reproduce the issue, can you provide more details about the issue? Thanks!

**Comment by mattst88** [comment] 2023-02-08 17:21
I confirm the issue still exists on current master. Configure and build with:

````sh
$ CFLAGS="-O2 -march=native -flto=auto -pipe" CXXFLAGS="$CFLAGS" cmake -S . -B build -G Ninja
$ ninja -C build -v
````

The `-flto` flag is what allows the compiler to recognize the issue.

````
[1524/1524] : && /usr/bin/c++ -fPIC -O2 -march=native -flto=auto -pipe -Wreorder -Wsign-promo -Wnon-virtual-dtor -Wno-invalid-offsetof -fvisibility-inlines-hidden -fno-use-cxa-atexit -frtti -fexceptions -fpermissive -fcheck-new -std=c++1y -std=c++11 -O3 -DNDEBUG  -Wl,--no-as-needed -Wl,--gc-sections -z relro -z now -fPIC -fstack-protector -shared -Wl,-soname,iHD_drv_video.so -o media_driver/iHD_drv_video.so @CMakeFiles/iHD_drv_video.rsp  && :
/root/projects/intel/media-driver/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:30: warning: type ‘struct KernelHeader’ violates the C++ One Definition Rule [-Wodr]
   30 | struct KernelHeader
      | 
/root/projects/intel/media-driver/media_driver/agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp:39: note: a different type is defined in another translation unit
   39 | struct KernelHeader {
      | 
/root/projects/intel/media-driver/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:32: note: the first difference of corresponding definitions is field ‘m_kernelCount’
   32 |     uint32_t m_kernelCount;
      | 
/root/projects/intel/media-driver/media_driver/agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp:40: note: a field of same name but different type is defined in another translation unit
   40 |     int m_kernelCount;
      | 
/root/projects/intel/media-driver/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:30: note: type ‘uint32_t’ should match type ‘int’
   30 | struct KernelHeader
      | 
/root/projects/intel/media-driver/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:568: warning: type ‘struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS’ violates the C++ One Definition Rule [-Wodr]
  568 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
      | 
/root/projects/intel/media-driver/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_common.h:31: note: a different type is defined in another translation unit
   31 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
      | 
/root/projects/intel/media-driver/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:570: note: the first difference of corresponding definitions is field ‘pSurfInput’
  570 |     PVPHAL_SURFACE                  pSurfInput;
      | 
/root/projects/intel/media-driver/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_common.h:33: note: a field of same name but different type is defined in another translation unit
   33 |     PVP_SURFACE                     pSurfInput;
      | 
/root/projects/intel/media-driver/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:568: note: type ‘struct VPHAL_SURFACE *’ should match type ‘struct VP_SURFACE *’
  568 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
      |````

**Comment by VickyZengg** [comment] 2023-02-13 06:12
> I confirm the issue still exists on current master. Configure and build with:
> 
> ```shell
> $ CFLAGS="-O2 -march=native -flto=auto -pipe" CXXFLAGS="$CFLAGS" cmake -S . -B build -G Ninja
> $ ninja -C build -v
> ```
> 
> The `-flto` flag is what allows the compiler to recognize the issue.
> 
> ```
> [1524/1524] : && /usr/bin/c++ -fPIC -O2 -march=native -flto=auto -pipe -Wreorder -Wsign-promo -Wnon-virtual-dtor -Wno-invalid-offsetof -fvisibility-inlines-hidden -fno-use-cxa-atexit -frtti -fexceptions -fpermissive -fcheck-new -std=c++1y -std=c++11 -O3 -DNDEBUG  -Wl,--no-as-needed -Wl,--gc-sections -z relro -z now -fPIC -fstack-protector -shared -Wl,-soname,iHD_drv_video.so -o media_driver/iHD_drv_video.so @CMakeFiles/iHD_drv_video.rsp  && :
> /root/projects/intel/media-driver/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:30: warning: type ‘struct KernelHeader’ violates the C++ One Definition Rule [-Wodr]
>    30 | struct KernelHeader
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp:39: note: a different type is defined in another translation unit
>    39 | struct KernelHeader {
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:32: note: the first difference of corresponding definitions is field ‘m_kernelCount’
>    32 |     uint32_t m_kernelCount;
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp:40: note: a field of same name but different type is defined in another translation unit
>    40 |     int m_kernelCount;
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp:30: note: type ‘uint32_t’ should match type ‘int’
>    30 | struct KernelHeader
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:568: warning: type ‘struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS’ violates the C++ One Definition Rule [-Wodr]
>   568 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
>       | 
> /root/projects/intel/media-driver/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_common.h:31: note: a different type is defined in another translation unit
>    31 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:570: note: the first difference of corresponding definitions is field ‘pSurfInput’
>   570 |     PVPHAL_SURFACE                  pSurfInput;
>       | 
> /root/projects/intel/media-driver/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_common.h:33: note: a field of same name but different type is defined in another translation unit
>    33 |     PVP_SURFACE                     pSurfInput;
>       | 
> /root/projects/intel/media-driver/media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.h:568: note: type ‘struct VPHAL_SURFACE *’ should match type ‘struct VP_SURFACE *’
>   568 | typedef struct _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS
>       |````
> ```

May I know what OS and gcc version you are using? Can you provide more details? Thanks a lot!

**Comment by mattst88** [comment] 2023-02-13 15:11
Gentoo Linux and gcc-12.

Are you having trouble reproducing the issue?

**Comment by haichund1** [comment] 2023-03-02 08:05
> Gentoo

does issue only happen on Gentoo linux? what's OS ver?

**Comment by mattst88** [comment] 2023-03-02 15:10
No, it doesn't happen only on Gentoo.

Please just try to reproduce it with the instructions I already gave. It's a legitimate problem in the code. E.g. there are multiple different structures named `struct KernelHeader`.

**Comment by VickyZengg** [comment] 2023-04-19 08:44
The fix already merged. Can you help verify it? Thanks a lot!
https://github.com/intel/media-driver/commit/35235c25843b5191fd7b49f5a26b63f019a609a7

**Comment by mattst88** [comment] 2023-04-19 22:04
Thanks! Looks fixed to me.

**Comment by VickyZengg** [comment] 2023-04-20 02:00
> Thanks! Looks fixed to me.

Thanks you!
@ArchangeGabriel  can you help verify and close this issue? Thanks a lot!

**Comment by Sherry-Lin** [comment] 2023-05-10 07:10
I'm going to close this issue which has been fixed in https://github.com/intel/media-driver/commit/35235c25843b5191fd7b49f5a26b63f019a609a7. Please feel free to re-open it if any new issues found. Thanks.

**Closed by Sherry-Lin** 2023-05-10 07:10 UTC
Labels: Build, Common
