### ISSUE TITLE
[Bug]: encode on TGL results in spoiled video with GuC and HuC enabled, kernel 5.17

### ISSUE THREAD

**Issue by georgnistor** [intel/media-driver#1430] opened 2022-06-07 16:52 UTC
### What happened?

Hello,

My cpu is corei9-11900T.

I try to encode with hevc_vaapi but I got the video spoiled.

Here is the command I use:
`ffmpeg -y -vaapi_device /dev/dri/card0  -i  input_file.mkv -vf 'format=nv12,hwupload' -c:v hevc_vaapi  -b:v 6000K  -c:a copy  out.mp4`

### What's the usage scenario when you are seeing the problem?

Transcode for media delivery, Content Creation

### Debug Information

here are my specs:

`
sudo pacman -Ss intel-media-driver
community/intel-media-driver 22.4.1-1 [installed]
    Intel Media Driver for VAAPI — Broadwell+ iGPUs
`

` uname -r                                                                                                                             
5.17.9-1-MANJARO
 sudo dmesg |grep i915                                                                                                                 
[sudo] password for george: 
[    6.555233] fb0: switching to i915 from EFI VGA
[    6.557121] i915 0000:00:02.0: vgaarb: deactivate vga console
[    6.586626] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    6.589025] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/rkl_dmc_ver2_03.bin (v2.3)
[    6.622807] i915 0000:00:02.0: [drm] GuC firmware i915/tgl_guc_62.0.0.bin version 62.0 submission:enabled
[    6.622814] i915 0000:00:02.0: [drm] GuC SLPC: enabled
[    6.622817] i915 0000:00:02.0: [drm] HuC firmware i915/tgl_huc_7.9.3.bin version 7.9 authenticated:yes
[    6.623025] i915 0000:00:02.0: [drm] GuC RC: enabled
[    6.645676] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[    6.683450] fbcon: i915drmfb (fb0) is primary device
[    6.683457] i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device
[    6.759978] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])
 sudo cat /sys/kernel/debug/dri/0/gt/uc/guc_info                                                                                        ✔ 
GuC firmware: i915/tgl_guc_62.0.0.bin
        status: RUNNING
        version: wanted 62.0, found 62.0
        uCode: 325632 bytes
        RSA: 256 bytes

GuC status 0x800300ec:
        Bootrom status = 0x76
        uKernel status = 0x0
        MIA Core status = 0x3

Scratch registers:
         0:     0x0
         1:     0x1673d3
         2:     0x0
         3:     0x4
         4:     0x40
         5:     0x2f4
         6:     0x0
         7:     0x0
         8:     0x0
         9:     0x0
        10:     0x0
        11:     0x0
        12:     0x0
        13:     0x0
        14:     0x0
        15:     0x0

GuC log relay not created
CT enabled
H2G Space: 2180
Head: 219
Tail: 219
G2H Space: 12284
Head: 1027
Tail: 1027
GuC Number Outstanding Submission G2H: 0
GuC tasklet count: 0

Requests in GuC submit tasklet:

Global scheduling policies:
  DPC promote time   = 500000
  Max num work items = 15
  Flags              = 0
 sudo cat /sys/kernel/debug/dri/0/gt/uc/huc_info                                                                                        ✔ 
HuC firmware: i915/tgl_huc_7.9.3.bin
        status: RUNNING
        version: wanted 7.9, found 7.9
        uCode: 589504 bytes
        RSA: 256 bytes
HuC status: 0x00090001

vainfo                                                                                                                                 ✔ 
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointEncSlice
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSlice
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointEncSlice
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
`
`

**Comment by georgnistor** [comment] 2022-06-07 17:02
`vainfo                                                                                                                                 ✔ 
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointEncSlice
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSlice
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointEncSlice
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
`

**Comment by XinfengZhang** [comment] 2022-06-08 00:51
what kind of spoiled video? could attach a picture of the video?

**Comment by georgnistor** [comment] 2022-06-08 00:57
I attach the screenshot of the output.
![Screenshot_20220608_035452](https://user-images.githubusercontent.com/43266416/172508675-aa68f7f1-99cb-45d9-a66e-d565b209da19.png)

**Comment by Xiaogangli-intel** [comment] 2022-06-09 04:24
Hi @georgnistor, what is the probability of this issue happening? we did 100 times, and didn't reproduce this issue. Did you tried other steams?

**Comment by georgnistor** [comment] 2022-06-09 07:19
Hi, @Xiaogangli-intel ,

In my case it happens always on my intel 11900T.
I have tried different streams. It happens always when hevc_vaapi codec.

**Comment by Xiaogangli-intel** [comment] 2022-06-13 01:44
Thanks @babam86, @georgnistor could you try the latest FFmpeg?

**Comment by georgnistor** [comment] 2022-06-13 07:42
I have tried with ffmpeg 4.2.1 and 5.0
I have the same problem.

**Comment by Xiaogangli-intel** [comment] 2022-06-16 09:01
I tried again use the same command line with you, still cannot reproduce. The difference between us is I use ubuntu and you use Arch, I will try to setup a Arch, and try again.

**Comment by XinfengZhang** [comment] 2023-05-08 03:25
seems could not reproduce the issue , and no more info. I close the issue, please feel free to re-open it if there are any concern, or the issue still could be reproduced.,

**Closed by XinfengZhang** 2023-05-08 03:25 UTC
Labels: Encode, Need Info, HEVC
