### ISSUE TITLE
[Bug]: FFmpeg vaapi max qp doesn't work with bitrate control mode in AVCe.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#1659] opened 2023-05-08 07:01 UTC
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

None

### What happened?

1. Linux
2. Use libva/media-driver/ffmpeg master code
3. Use -qmax to specific max qp and -rc_mode set to CBR/VBR/QVBR. Example ffmpeg cmdline:
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -pix_fmt yuv420p -s:v 1920x1080 -r:v 30 -i 1080p_blue_sky_1920x1080_I420.yuv -vf 'format=nv12,hwupload' -c:v h264_vaapi -profile:v main -rc_mode VBR -qmax 30 -g 30 -b:v 2000k -vframes 100 -y out.h264
4. Expect result is the MB qp of out.h264 should be less than 30.
5. Tested with qmax set to 0 and 30 on CFL, the output bitstream get the same md5sum.

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

None

**Comment by intel-mediadev** [comment] 2023-05-08 13:27
Auto Created VSMGWL-64376 for further analysis.

**Comment by DenWolf** [comment] 2023-05-09 22:17
Hello @feiwan1 ,

**1** - I want to clarify - do I right understand that you run the same command-line (from your example) with "-qmax 30" and "-qmax 0" and got 2 exact matched bitstreams?
If yes, could you please help to share this bitstream for analysis? Maybe upload to some external share-folder or send it to my email - denis.volkov@intel.com ?
**1.1** - did you tried another "qmax" values except 30 and 0 ?

**2** - question about the platform - do I right understand that you have tested it on CFL?
Are interesting for CFL only, or maybe some newer platforms as well - ICL / TGL / ATS-M ... ?

Best regards,
Denis

**Comment by feiwan1** [comment] 2023-05-10 01:54
> hi Fei, what's the platform?

I only tried on Coffee Lake and Tiger Lake, all have this issue.

**Comment by feiwan1** [comment] 2023-05-10 02:13
Hi @DenWolf , for your questions:

> Hello @feiwan1 ,
> 
> **1** - I want to clarify - do I right understand that you run the same command-line (from your example) with "-qmax 30" and "-qmax 0" and got 2 exact matched bitstreams? If yes, could you please help to share this bitstream for analysis? In case if you will not able to attached on GitHub - maybe upload to some external share-folder or send it to my email - [denis.volkov@intel.com](mailto:denis.volkov@intel.com) ? 

Yes, I got 2 exact matched bitstreams with "-qmax 30" and "-qmax 0". You can use ffmpeg internel YUV pattern to reproduce this issue very quickly in your side which doesn't need any input yuv file:

$ ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f lavfi -i testsrc=size=1920x1080 -vf 'format=nv12,hwupload' -c:v h264_vaapi -profile:v main -rc_mode VBR -qmax 0 -g 30 -b:v 1000k -vframes 100 -y out_max0_vbr1000.h264

$ ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f lavfi -i testsrc=size=1920x1080 -vf 'format=nv12,hwupload' -c:v h264_vaapi -profile:v main -rc_mode VBR -qmax 20 -g 30 -b:v 1000k -vframes 100 -y out_max20_vbr1000.h264

$ ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f lavfi -i testsrc=size=1920x1080 -vf 'format=nv12,hwupload' -c:v h264_vaapi -profile:v main -rc_mode VBR -qmax 20 -g 30 -b:v 1000k -vframes 100 -y out_max30_vbr1000.h264

$ root@tgl:~/media/qvbr# md5sum out_max*
c0fe6fabc3e2ec1f1ab29cff25fafafe  out_max0_vbr1000.h264
c0fe6fabc3e2ec1f1ab29cff25fafafe  out_max20_vbr1000.h264
c0fe6fabc3e2ec1f1ab29cff25fafafe  out_max30_vbr1000.h264

And I will send you the 3 bitstreams generated on Tiger Lake through Email.

>**1.1** - did you tried another "qmax" values except 30 and 0 ?

Yes, use 10 and 20 got the same exact matched bitstreams too.

> 
> **2** - question about the platform - do I right understand that you have tested it on CFL? Are interesting for CFL only, or maybe some newer platforms as well - ICL / TGL / ATS-M ... ?

I tried on CoffeLake and TigerLake, all have this issue. We cares about newer platforms too.

> 
> Best regards, Denis

**Comment by DenWolf** [comment] 2023-05-22 14:12
Short summary for today (May 22) :
- analyzed the streams shared by @feiwan1  - confirmed that MaxQP feature was not applied
- checked TGL Windows (via MSDK/VPL) - feature is working (both for VME and VDEnc Encoders)
- checked Linux source code in Media Driver - MaxQP should applied as well


The next steps:
- check Linux TGL via MSDK/VPL first via MSDK tools 
- check ffmpeg QSV (also via MSDK)
- check ffmpeg vaapi

**Comment by DenWolf** [comment] 2023-05-30 10:16
Hi @feiwan1 ,

Issue has been root caused as ffmpeg specific (different order of setting PicParams and MiscParams - MinMaxQP settings were overwritten) and fixed by the next patch (already merged into media driver OS repo - https://github.com/intel/media-driver/commit/b2ab41b3fd167644643be3f3471c29ea4a8b22dc

Please help to verify this fix.

**Comment by DenWolf** [comment] 2023-05-30 10:19
Hi @pearsche ,

Not every Encoder supports MinMaxQP feature, originally it was introduced for AVC/HEVC. I 99% sure that VP9 encoder does not support it, so the behavior with ignoring MaxQP parameters is expected.

Please help to describe - which scenario do you want to use and which results do you want to achieve - maybe we can help to achieve it with a different BRC settings/features.

**Comment by feiwan1** [comment] 2023-06-01 06:59
Thanks @DenWolf, your fix works for me.

**Comment by OttoYang** [comment] 2023-06-07 01:04
Thanks @DenWolf and @feiwan1 , I will close this issue.

**Closed by OttoYang** 2023-06-07 01:04 UTC
Labels: Encode, AVC
