### ISSUE TITLE
Tabs with embed video crash on Firefox 94.0.1 (64-bit) on Manjaro

### ISSUE THREAD

**Issue by jtux270** [intel/media-driver#1289] opened 2021-11-16 19:34 UTC
## System information
- CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
- GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01)
- kernel 5.15.0-1-MANJARO

### Describe the current behavior
Firefox tab crashes wile trying to open the page with the embed video, can't watch embed videos on Reddit, the example page[1] from Arch wiki [2] is crashing also
[1] http://demo.nimius.net/video_test/
[2] https://wiki.archlinux.org/title/Firefox#Multimedia_playback

### Describe the expected behavior
Start playing video on pressing the triangle Play button

## Debug information
- libva 2.13.0-1, libva-utils 2.12.0-1, gmmlib 21.2.1-1, media-driver 21.3.2-1
- by-path  card0  renderD128
- vainfo log 
```
vainfo: VA-API version: 1.13 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.3.2 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP

```
The Firefox crash log points thrice to iHD_drv_video.so, if you need that report, I can attach the file or paste it on some third party site since it's too big
- Could you provide libva trace log if possible? No log
- Do you want to contribute a PR? (yes/no): no
Edit: can't play YouTube

**Comment by XinfengZhang** [comment] 2021-11-23 08:05
how about #1293

**Comment by XinfengZhang** [comment] 2021-12-05 12:49
I guess the issue is similar with #854, #1307, #1283,.
your platform is TGL, suppose latest media driver master (with commit 4e70cd6 ) should work.

(ps, if you are using the older platform before TGL, please refer the PR #1293 )

**Comment by Jexu** [comment] 2022-12-02 04:18
Do you help try if latest driver solves your issue?

**Comment by XinfengZhang** [comment] 2023-05-08 12:42
the issue should already been fixed, I close it, any concern , feel free to reopen it.

**Closed by XinfengZhang** 2023-05-08 12:42 UTC
Labels: Need Info
