### ISSUE TITLE
[Bug]: build failure for media_libva_putsurface_linux.cpp

### ISSUE THREAD

**Issue by renwu58** [intel/media-driver#1472] opened 2022-08-13 21:35 UTC
### Which component impacted?

Build

### What happened?

OS:
Jeffy@Jeffy-PC:~/soft/media-driver/build$ uname -a
Linux Jeffy-PC 5.15.34-amd64-desktop #2 SMP Mon May 16 16:31:30 CST 2022 x86_64 GNU/Linux

I have already build the latest verison of libva with X11 and GMMLib everything is seems fine. but when build the package following the instruction: https://01.org/linuxmedia/quickstart/linux-vaapi-videostack-environment build the media-driver have following error.

```
Jeffy@Jeffy-PC:~/soft/media-driver/build$ make -j8
[  0%] Built target iHD_drv_video_CP
[  0%] Built target iHD_drv_video_SSE2
[  0%] Built target iHD_drv_video_SSE4
[  2%] Built target igfxcmrt
[  8%] Built target iHD_drv_video_mos
Consolidate compiler generated dependencies of target iHD_drv_video_COMMON
[ 23%] Built target iHD_drv_video_VP
[ 67%] Built target iHD_drv_video_CODEC
[ 67%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/ddi/media_libva_putsurface_linux.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/renderhal/renderhal_dsh_specific.c.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/vp/ddi/media_libva_vp.c.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/vp/ddi/media_libva_vp_tools.c.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/vp/hal/vphal_common_specific.c.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/renderhal/renderhal_linux.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/hw/mhw_mi_linux.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/vp/hal/vphal_render_common_specific.c.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/shared/hal_oca_interface.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen8/ddi/media_libva_caps_g8.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen8/ddi/media_sysinfo_g8.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen8/ddi/media_sku_wa_g8.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen9/ddi/media_libva_caps_g9.cpp.o
[ 68%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen9/ddi/media_sysinfo_g9.cpp.o
[ 69%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen9/ddi/media_sku_wa_g9.cpp.o
[ 69%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/gen9_bxt/ddi/media_libva_caps_g9_bxt.cpp.o
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp: In function ‘bool output_dri_init(VADriverContextP)’:
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:166:18: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     mediaDrvCtx->dri_output = nullptr;
                  ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:178:18: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     mediaDrvCtx->dri_output = (va_dri_output*) calloc(1, sizeof(struct va_dri_output));
                  ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:179:23: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     if (!mediaDrvCtx->dri_output){
                       ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:183:18: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     mediaDrvCtx->dri_output->handle = dso_open(LIBVA_X11_NAME);
                  ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:184:23: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     if (!mediaDrvCtx->dri_output->handle){
                       ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:185:27: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
         free(mediaDrvCtx->dri_output);
                           ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:186:22: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
         mediaDrvCtx->dri_output = nullptr;
                      ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:190:31: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     dso_handle = mediaDrvCtx->dri_output->handle;
                               ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:191:32: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     dri_vtable = &mediaDrvCtx->dri_output->vtable;
                                ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:193:32: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
         dso_close(mediaDrvCtx->dri_output->handle);
                                ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:194:27: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
         free(mediaDrvCtx->dri_output);
                           ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:195:22: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
         mediaDrvCtx->dri_output = nullptr;
                      ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp: In function ‘VAStatus DdiCodec_PutSurfaceLinuxVphalExt(VADriverContextP, VASurfaceID, void*, int16_t, int16_t, uint16_t, uint16_t, int16_t, int16_t, uint16_t, uint16_t, VARectangle*, uint32_t, uint32_t)’:
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:270:33: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     if (nullptr == mediaDrvCtx->X11FuncTable                   ||
                                 ^~~~~~~~~~~~
                                 SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:271:33: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
         nullptr == mediaDrvCtx->X11FuncTable->pfnXCreateGC     ||
                                 ^~~~~~~~~~~~
                                 SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:272:33: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
         nullptr == mediaDrvCtx->X11FuncTable->pfnXFreeGC       ||
                                 ^~~~~~~~~~~~
                                 SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:273:33: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
         nullptr == mediaDrvCtx->X11FuncTable->pfnXCreateImage  ||
                                 ^~~~~~~~~~~~
                                 SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:274:33: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
         nullptr == mediaDrvCtx->X11FuncTable->pfnXDestroyImage ||
                                 ^~~~~~~~~~~~
                                 SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:275:33: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
         nullptr == mediaDrvCtx->X11FuncTable->pfnXPutImage)
                                 ^~~~~~~~~~~~
                                 SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:280:54: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     pfn_XCreateGC     = (TypeXCreateGC)(mediaDrvCtx->X11FuncTable->pfnXCreateGC);
                                                      ^~~~~~~~~~~~
                                                      SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:281:52: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     pfn_XFreeGC       = (TypeXFreeGC)(mediaDrvCtx->X11FuncTable->pfnXFreeGC);
                                                    ^~~~~~~~~~~~
                                                    SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:282:57: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     pfn_XCreateImage  = (TypeXCreateImage)(mediaDrvCtx->X11FuncTable->pfnXCreateImage);
                                                         ^~~~~~~~~~~~
                                                         SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:283:58: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     pfn_XDestroyImage = (TypeXDestroyImage)(mediaDrvCtx->X11FuncTable->pfnXDestroyImage);
                                                          ^~~~~~~~~~~~
                                                          SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:284:54: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     pfn_XPutImage     = (TypeXPutImage)(mediaDrvCtx->X11FuncTable->pfnXPutImage);
                                                      ^~~~~~~~~~~~
                                                      SkuTable
In file included from /home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:47:
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp: In function ‘VAStatus DdiCodec_PutSurfaceLinuxHW(VADriverContextP, VASurfaceID, void*, int16_t, int16_t, uint16_t, uint16_t, int16_t, int16_t, uint16_t, uint16_t, VARectangle*, uint32_t, uint32_t)’:
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:384:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     DDI_CHK_NULL(mediaCtx->dri_output, "Null mediaDrvCtx->dri_output", VA_STATUS_ERROR_INVALID_PARAMETER);
                            ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:384:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->dri_output, "Null mediaDrvCtx->dri_output", VA_STATUS_ERROR_INVALID_PARAMETER);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:389:55: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘dri_output’
     struct dri_vtable * const dri_vtable = &mediaCtx->dri_output->vtable;
                                                       ^~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:556:39: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘PutSurfaceRenderMutex’; did you mean ‘SurfaceMutex’?
     DdiMediaUtil_LockMutex(&mediaCtx->PutSurfaceRenderMutex);
                                       ^~~~~~~~~~~~~~~~~~~~~
                                       SurfaceMutex
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:560:45: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘PutSurfaceRenderMutex’; did you mean ‘SurfaceMutex’?
         DdiMediaUtil_UnLockMutex(&mediaCtx->PutSurfaceRenderMutex);
                                             ^~~~~~~~~~~~~~~~~~~~~
                                             SurfaceMutex
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:565:41: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘PutSurfaceRenderMutex’; did you mean ‘SurfaceMutex’?
     DdiMediaUtil_UnLockMutex(&mediaCtx->PutSurfaceRenderMutex);
                                         ^~~~~~~~~~~~~~~~~~~~~
                                         SurfaceMutex
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:568:39: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘PutSurfaceSwapBufferMutex’
     DdiMediaUtil_LockMutex(&mediaCtx->PutSurfaceSwapBufferMutex);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:570:41: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘PutSurfaceSwapBufferMutex’
     DdiMediaUtil_UnLockMutex(&mediaCtx->PutSurfaceSwapBufferMutex);
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:47:
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp: In function ‘VAStatus DdiMedia_PutSurfaceLinuxSW(VADriverContextP, VASurfaceID, void*, int16_t, int16_t, uint16_t, uint16_t, int16_t, int16_t, uint16_t, uint16_t, VARectangle*, uint32_t, uint32_t)’:
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:824:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     DDI_CHK_NULL(mediaCtx->X11FuncTable, "nullptr X11FuncTable", VA_STATUS_ERROR_INVALID_CONTEXT);
                            ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:824:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->X11FuncTable, "nullptr X11FuncTable", VA_STATUS_ERROR_INVALID_CONTEXT);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:825:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXCreateGC, "nullptr pfnXCreateGC", VA_STATUS_ERROR_INVALID_CONTEXT);
                            ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:825:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXCreateGC, "nullptr pfnXCreateGC", VA_STATUS_ERROR_INVALID_CONTEXT);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:826:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXFreeGC, "nullptr pfnXFreeGC", VA_STATUS_ERROR_INVALID_CONTEXT);
                            ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:826:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXFreeGC, "nullptr pfnXFreeGC", VA_STATUS_ERROR_INVALID_CONTEXT);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:827:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXCreateImage, "nullptr pfnXCreateImage", VA_STATUS_ERROR_INVALID_CONTEXT);
                            ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:827:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXCreateImage, "nullptr pfnXCreateImage", VA_STATUS_ERROR_INVALID_CONTEXT);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:828:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXDestroyImage, "nullptr pfnXDestroyImage", VA_STATUS_ERROR_INVALID_CONTEXT);
                            ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:828:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXDestroyImage, "nullptr pfnXDestroyImage", VA_STATUS_ERROR_INVALID_CONTEXT);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:829:28: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXPutImage, "nullptr pfnXPutImage", VA_STATUS_ERROR_INVALID_CONTEXT);
                            ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_util.h:455:9: note: in definition of macro ‘DDI_CHK_CONDITION’
     if (condition) {                                                          \
         ^~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:829:5: note: in expansion of macro ‘DDI_CHK_NULL’
     DDI_CHK_NULL(mediaCtx->X11FuncTable->pfnXPutImage, "nullptr pfnXPutImage", VA_STATUS_ERROR_INVALID_CONTEXT);
     ^~~~~~~~~~~~
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:831:69: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     TypeXCreateGC     pfn_XCreateGC     = (TypeXCreateGC)(mediaCtx->X11FuncTable->pfnXCreateGC);
                                                                     ^~~~~~~~~~~~
                                                                     SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:832:67: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     TypeXFreeGC       pfn_XFreeGC       = (TypeXFreeGC)(mediaCtx->X11FuncTable->pfnXFreeGC);
                                                                   ^~~~~~~~~~~~
                                                                   SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:833:72: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     TypeXCreateImage  pfn_XCreateImage  = (TypeXCreateImage)(mediaCtx->X11FuncTable->pfnXCreateImage);
                                                                        ^~~~~~~~~~~~
                                                                        SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:834:73: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     TypeXDestroyImage pfn_XDestroyImage = (TypeXDestroyImage)(mediaCtx->X11FuncTable->pfnXDestroyImage);
                                                                         ^~~~~~~~~~~~
                                                                         SkuTable
/home/Jeffy/soft/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp:835:69: error: ‘struct DDI_MEDIA_CONTEXT’ has no member named ‘X11FuncTable’; did you mean ‘SkuTable’?
     TypeXPutImage     pfn_XPutImage     = (TypeXPutImage)(mediaCtx->X11FuncTable->pfnXPutImage);
                                                                     ^~~~~~~~~~~~
                                                                     SkuTable
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/build.make:3856: media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/linux/common/ddi/media_libva_putsurface_linux.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:225: media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

The package build failure and cannot install

## Packages verison

libva: 2.15.0
libva-utils: 2.15.0
gmmlib: 2.15.0
media-driver:  latest master branch 22.5.3 

## ls /dev/dri
```
Jeffy@Jeffy-PC:~/soft/media-driver/build$ ls /dev/dri
ls: cannot access '/dev/dri': No such file or directory
```

```
Jeffy@Jeffy-PC:~/soft/media-driver/build$ vainfo 
error: failed to initialize display
```

**Comment by XinfengZhang** [comment] 2022-08-15 13:46
suppose it is because
#if !defined(ANDROID) && defined(X11_FOUND) 
so, it is X11_FOUND is false

**Comment by kingskill** [comment] 2022-09-07 09:14
> suppose it is because #if !defined(ANDROID) && defined(X11_FOUND) so, it is X11_FOUND is false

So how to fix it?

**Comment by cqian2** [comment] 2022-11-23 06:59
Hi, @renwu58 ,

Would you please help verify it with PR#https://github.com/intel/media-driver/pull/1527 ?


Thanks
Chunqiang

**Comment by cqian2** [comment] 2022-11-30 00:56
I tried PR#1527 but couldn't reproduce the issue. Close it now.
Feel free to reopen it if further reproducibility.

**Closed by cqian2** 2022-11-30 00:56 UTC
Labels: P2, Build, Common
