### ISSUE TITLE
[ICLLP][AVC lowe power Encode] AVC low power encode brc fail due to huc loading fail

### ISSUE THREAD

**Issue by emmaqiaogn** [intel/media-driver#328] opened 2018-09-26 07:53 UTC
build and install https://github.com/intel/media-driver
build https://github.com/intel/libva-utils

mv_encoder_adv -i cityLetters_720x480_30_1_500.yuv -o cityLetters_720x480_30_1_500_mvencadv.264 --file-fmt i420 --encode avc --SourceWidth 720 --SourceHeight 480 --NumFrames 500 --RefFrameType 2 --FrameRate 29.97 --EncoderInput NV12 --EncoderOutput NV12 --BitRate 11099889 --MaxBitRate 0 --MinBitRate 11099889 --TargetBitRate 11099889 --RateControl 1 --TargetUsage 1 --MAD 0 --MADInterval 1 --AVBRAccuracy 100 --AVBRConvergence 1 --InstantBitRateCheck 0 --InstantBitRateAccuracy 250 --InstantBitRateConvergence 0 --GOPBRCResetInterval 0 --vdenc --PictureCodingType 0 --EntropyCodingMode 0 --CabacInitIDC 1 --DeblockingIDC 0 --ProfileIDC 77 --LevelIDC 32 --ChromaFormatIDC 1 --GOPPicSize 36 --GOPRefDist 1 --BPyramid 0 --NumRefFrames 2 --SliceStructure 2 --NumSlicesResetInterval 0 --NumSlices 30 --NumSlicesForReset 1,1,1,1,1,1,1,1 --PSliceType 5 --BSliceType 6 --ISliceType 7 --ISliceQP 25 --PSliceQP 25 --BSliceQP 25 --SliceQpDelta 0 --MBBRC 1 

ERROR   :FrameModeWrapper: [trans] ERROR:ENCODE: attribute not supported(issue #1)
ERROR   :FrameModeWrapper: [trans] ERROR:ENCODE: Encoder failed during configuration
ERROR   :FrameModeWrapper: [trans] ERROR:COMMON: Fail to open encode accelerator
ERROR   :FrameModeWrapper: [trans] ERROR:COMMON: Builder is failed... deleting created media components
ERROR   :FrameModeWrapper: [trans] ERROR:COMMON: Fail to create Encoder Product

**Comment by emmaqiaogn** [comment] 2018-09-26 07:56
set boot/grub.cfg
i915.enable_guc=3

**Comment by EwoutH** [comment] 2019-05-20 21:32
Any update on this issue?

**Comment by XinfengZhang** [comment] 2020-05-14 05:57
@emmaqiaogn , could we close the issue

**Comment by XinfengZhang** [comment] 2020-06-07 14:26
close it, it could not reproduced on latest kernel version , such as 5.4

**Closed by XinfengZhang** 2020-06-07 14:26 UTC
Labels: in progress
