### ISSUE TITLE
chromium-vaapi (ffmpeg v4.1): "Failed syncing surface VA error: internal decoding error"

### ISSUE THREAD

**Issue by enihcam** [intel/media-driver#469] opened 2018-12-15 03:55 UTC
Web video crashes when dragging progress bar (chromium-vaapi with HW accel. enabled, ffmpeg v4.1)

```
[1:15:1215/114722.869293:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.870482:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.871596:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.872317:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.873042:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.874713:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.875911:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.879423:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Failed to send video packet for decoding: timestamp=2419083 duration=41708 size=2625 side_data_size=0 is_key_frame=0 encrypted=0 discard_padding (us)=(0, 0)"}
[1:15:1215/114722.879981:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.880920:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decoder reinitialization failed"}
[1:15:1215/114722.881219:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:15:1215/114722.881533:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Format conversion failed."}
[1:1:1215/114722.881941:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
[2976:2983:1215/114729.391654:ERROR:socket_stream.cc(219)] Closing stream with result -2
[3006:3006:1215/114808.508607:ERROR:vaapi_wrapper.cc(1107)] Failed syncing surface VA error: internal decoding error
[1:15:1215/114808.509896:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
[1:1:1215/114808.513472:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
```

Contents of chrome://gpu: 
```
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Force enabled
Native GpuMemoryBuffers: Hardware accelerated
Out-of-process Rasterization: Disabled
Hardware Protected Video Decode: Hardware accelerated
Rasterization: Hardware accelerated on all pages
Skia Deferred Display List: Disabled
Skia Renderer: Disabled
Surface Control: Disabled
Surface Synchronization: Enabled
Video Decode: Hardware accelerated
Viz Service Display Compositor: Enabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Driver Bug Workarounds
adjust_src_dst_region_for_blitframebuffer
clear_uniforms_before_first_program_use
count_all_in_varyings_packing
decode_encode_srgb_for_generatemipmap
disable_framebuffer_cmaa
disable_post_sub_buffers_for_onscreen_surfaces
msaa_is_slow
scalarize_vec_and_mat_constructor_args
disabled_extension_GL_ARB_timer_query
disabled_extension_GL_EXT_timer_query
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
Problems Detected
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Mesa drivers in Linux handle varyings without static use incorrectly: 333885
Applied Workarounds: count_all_in_varyings_packing
Disable partial swaps on Mesa drivers (detected with GL_RENDERER): 339493
Applied Workarounds: disable_post_sub_buffers_for_onscreen_surfaces
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
On Intel GPUs MSAA performance is not acceptable for GPU rasterization: 527565
Applied Workarounds: msaa_is_slow
Timer queries crash on Intel GPUs on Linux: 540543, 576991
Applied Workarounds: disable(GL_ARB_timer_query), disable(GL_EXT_timer_query)
Use GL_INTEL_framebuffer_CMAA on ChromeOS: 535198
Applied Workarounds: disable_framebuffer_cmaa
Disable partial swaps on Mesa drivers (detected with GL_VERSION): 339493
Applied Workarounds: disable_post_sub_buffers_for_onscreen_surfaces
Decode and encode before generateMipmap for srgb format textures on os except macosx: 634519
Applied Workarounds: decode_encode_srgb_for_generatemipmap
adjust src/dst region if blitting pixels outside read framebuffer on Linux Intel: 664740
Applied Workarounds: adjust_src_dst_region_for_blitframebuffer
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Skia renderer is not used by default.
Disabled Features: skia_renderer
Skia deferred display list is not used by default.
Disabled Features: skia_deferred_display_list
Version Information
Data exported	2018-12-15T04:02:40.320Z
Chrome version	Chrome/71.0.3578.98
Operating system	Linux 4.19.9-2-clear
Software rendering list URL	https://chromium.googlesource.com/chromium/src/+/15234034d19b85dcd9a03b164ae89d04145d8368/gpu/config/software_rendering_list.json
Driver bug list URL	https://chromium.googlesource.com/chromium/src/+/15234034d19b85dcd9a03b164ae89d04145d8368/gpu/config/gpu_driver_bug_list.json
ANGLE commit id	unknown hash
2D graphics backend	Skia/71 7469a9341afab19271b8ef07af5c16a0f2c4ccc1-
Command Line	/usr/lib/chromium/chromium --ppapi-flash-version=32.0.0.101 --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --enable-accelerated-2d-canvas --enable-accelerated-mjpeg-decode --enable-accelerated-video --enable-features=CheckerImaging,VizDisplayCompositor --enable-gpu-async-worker-context --enable-gpu-memory-buffer-compositor-resources --enable-gpu-memory-buffer-video-frames --enable-gpu-rasterization --enable-native-gpu-memory-buffers --enable-zero-copy --enable-tcp-fast-open --enable-tile-compression --enable-simple-cache-backend --enable-viz --force-gpu-rasterization --ignore-gpu-blacklist --use-skia-deferred-display-list --use-skia-renderer --flag-switches-begin --no-pings --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --enable-accelerated-mjpeg-decode --enable-accelerated-video --enable-audio-focus --enable-fast-unload --enable-gpu-rasterization --enable-oop-rasterization --use-simple-cache-backend=on --enable-tcp-fastopen --enable-zero-copy --gpu-rasterization-msaa-sample-count=0 --ignore-gpu-blacklist --enable-lcd-text --num-raster-threads=4 --enable-smooth-scrolling --enable-features=CheckerImaging,VizDisplayCompositor,Av1Decoder,BloatedRendererDetection,ClientLoFi,DetectingHeavyPages,DrawOcclusion,ExpensiveBackgroundTimerThrottling,FontCacheScaling,ImprovedLanguageSettings,LazyFrameLoading,LazyImageLoading,NewAudioRenderingMixingStrategy,NoScriptPreviews,NoStatePrefetch,OptimizationHints,ParallelDownloading,ResourceLoadScheduler,ResourceLoadingHints,brotli-encoding --flag-switches-end
Driver Information
Initialization time	33
In-process GPU	false
Passthrough Command Decoder	false
Sandboxed	false
GPU0	VENDOR = 0x8086 [Intel Open Source Technology Center], DEVICE= 0x5916 [Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) ] *ACTIVE*
Optimus	false
AMD switchable	false
Driver vendor	Mesa
Driver version	18.2.6
Driver date	
GPU CUDA compute capability major version	0
Pixel shader version	1.30
Vertex shader version	1.30
Max. MSAA samples	16
Machine model name	
Machine model version	
GL_VENDOR	Intel Open Source Technology Center
GL_RENDERER	Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)
GL_VERSION	3.0 Mesa 18.2.6
GL_EXTENSIONS	GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_gpu_program_parameters GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_framebuffer_fetch GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays
Disabled Extensions	GL_ARB_timer_query GL_EXT_timer_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent
Disabled WebGL Extensions	
Window system binding vendor	SGI
Window system binding version	1.4
Window system binding extensions	GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_multisample GLX_EXT_create_context_es_profile GLX_EXT_create_context_es2_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_libglvnd GLX_EXT_no_config_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_OML_swap_method GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_INTEL_swap_event
Window manager	Openbox
XDG_CURRENT_DESKTOP	LXDE
GDMSESSION	LXDE
Compositing manager	No
Direct rendering	Yes
Reset notification strategy	0x8261
GPU process crash count	0
System visual ID	33
RGBA visual ID	382
Compositor Information
Tile Update Mode	Zero-copy
Partial Raster	Enabled
GpuMemoryBuffers Status
R_8	Software only
R_16	Software only
RG_88	Software only
BGR_565	Software only
RGBA_4444	Software only
RGBX_8888	Software only
RGBA_8888	Software only
BGRX_8888	Software only
BGRX_1010102	Software only
RGBX_1010102	Software only
BGRA_8888	Software only
RGBA_F16	Software only
YVU_420	Software only
YUV_420_BIPLANAR	Software only
UYVY_422	Software only
Display(s) Information
Info	Display[1881264395124802] bounds=[0,0 1920x1080], workarea=[78,0 1842x1080], scale=1, external.
Color space information	{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}
Bits per color component	8
Bits per pixel	24
Video Acceleration Information
Decode h264 baseline	up to 4096x4096 pixels
Decode h264 main	up to 4096x4096 pixels
Decode h264 high	up to 4096x4096 pixels
Decode vp8	up to 4096x4096 pixels
Decode vp9 profile0	up to 4096x4096 pixels
Encode h264 baseline	up to 4096x4096 pixels and/or 30.000 fps
Encode h264 main	up to 4096x4096 pixels and/or 30.000 fps
Encode h264 high	up to 4096x4096 pixels and/or 30.000 fps
```

Try the following video links:
https://www.billboard.com/video/janet-jackson-meets-bts-backstage-at-mnet-asian-music-awards-billboard-news-8490370
https://www.nhl.com/video/icymi-lundqvists-stellar-save/t-277350912/c-64029403

intel-vaapi-driver has no such issue.

**Comment by eero-t** [comment] 2019-01-16 17:16
> It looks like this issue only happens to WEBM format.
> MP4 format is good.

Both of these are containers formats, what's the actual failing codec, VP8?

(e.g. mediainfo program in Linux would give more info on the video format.)

Does "dragging progress bar" mean that failure happens at some specific position in video?

Can you reproduce the issue e.g. with FFmpeg or sample applications in MediaSDK?

**Comment by enihcam** [comment] 2019-01-17 01:58
Repo steps:
1. boot with Manjaro LiveCD:
2. yaourt -S intel-media-driver chromium-vaapi (or chromium-vaapi-bin)
3. change vaapi driver to iHD
4. enable hardware video acceleration in chromium about:flags
5. Try "dragging progress bar" for the the following videos:
https://www.billboard.com/video/janet-jackson-meets-bts-backstage-at-mnet-asian-music-awards-billboard-news-8490370
https://www.nhl.com/video/icymi-lundqvists-stellar-save/t-277350912/c-64029403

**Comment by widefox** [comment] 2019-01-25 15:55
I don't know about WEBM but MP4 fails e.g. mp4, 1920x1080, avc1.640028, 24fps. Same issue on up to date Fedora 29, kernel 5.0rc3, Chromium-vaapi Version 71.0.3578.98 (RPMFusion Build) chromium-vaapi (64-bit), iHD, HW accel enabled, ffmpeg v4.0.3 . Does not happen with unaccelerated Chrome 71, Chrome beta 72. YouTube videos H264 (to reproduce use h264ify extension). Default WEBM YouTube with VP9 (1920x1080, 2754k , vp9, 24fps,) is not hardware accelerated on this PC and does not have this bug.

**Comment by maximbaz** [comment] 2019-02-10 21:00
VA-API patch is now part of official Chromium on Arch Linux, so be aware that `chromium-vaapi` and `chromium-vaapi-bin` are obsolete now, also HW video acceleration is enabled by default so no need to mess with Chromium flags to get it enabled. 

This also means that the bug is suddenly more important because potentially more people are affected by this now 😉 

I can confirm that the issue can only be reproduced with H264 format, VP9 is working fine. I used `youtube-dl` to download a random youtube video in two formats, `(h264 1920x1080 60.000fps)` and `(vp9 1920x1080 60.000fps)`. Open both in Chromium from the local file system, then try to move forward in the video — H264 video will get stuck, and you won't be able to play it anymore, while VP9 video correctly continues playing from the new position.

Maybe a simpler way to reproduce the issue is to install [h264ify](https://chrome.google.com/webstore/detail/h264ify/aleakchihdccplidncghkekgioiakgal) extension, then just navigate to YouTube and play any video, click on "progress bar" to move further and video will get stuck.

This is what is printed in console at this time:

```
[18209:18209:0210/215931.479441:ERROR:vaapi_wrapper.cc(1149)] Failed syncing surface VA error: internal decoding error
[103:175:0210/215931.479643:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"VDA Error 4"}
[103:175:0210/215931.479788:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
[103:103:0210/215931.480022:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
```

**Comment by widefox** [comment] 2019-02-17 17:01
Confirm H264 seeking still broken in chromium-vaapi.x86_64                                                                         72.0.3626.81-2.fc29 libva-2.3.0-1.fc29.x86_64 intel-media-driver.x86_64                                                                         18.3.0-2.fc29  . chromium-vaapi is the package name in Fedora from rpmfusion (rpmfusion-free-updates). Note that currently F29 now needs downgrade of libva from 2.4 to 2.3  libva-2.4.0-2.fc29 -> libva-2.3.0-1.fc29 to enable acceleration, else will get warning "[4138:4138:0217/130657.111905:ERROR:vaapi_wrapper.cc(343)] This build of Chromium requires VA-API version 1.3, system version: 1.4"

**Comment by enihcam** [comment] 2019-02-22 05:23
Hi Intel, when will you start debugging on this?
latest chromium + latest media-driver does not resolve the issue.

**Comment by widefox** [comment] 2019-02-27 12:04
Appears fixed on Fedora 29 (rpmfusion testing) chromium-vaapi 72.0.3626.109 (RPMFusion Build) chromium-vaapi (64-bit), libva 1.4 . [enihcam](/enihcam) do you have details?

**Comment by maximbaz** [comment] 2019-02-27 12:39
Are you sure @widefox? I don't think there have been any releases in this repo, and Fedora's spec doesn't seem to use any new patches. Maybe you are accidentally using a different driver?

**Comment by widefox** [comment] 2019-02-28 14:40
> Are you sure @widefox? I don't think there have been any releases in this repo, and Fedora's spec doesn't seem to use any new patches. Maybe you are accidentally using a different driver?

@maximbaz Yes. Tested on 2 Intel i5/i7 laptops (5th gen and 2nd gen). Confirm no seeking problem now. I may have the hybrid driver installed now too when I didn't before I don't know, as I varied many things when I got the libva 1.3 and 1.4 version mismatch for a week which prevented hardware acceleration (as I reported above - which I presume the package maintainer should fix the chromium-vaapi package dependency so the matching 1.3 wouldn't be updated to an incompatible 1.4).

F29 updated from libva 1.3 -> 1.4 a weekish ago. That resulted in a version incompatibility with the then latest chromium-vaapi from RPMFusion and AFAIK the chromium from Fedora (as I reported above). Now the new RPMFusion chromium-vaapi 72.0.3626.109 is compiled with 1.4 (rather than 1.3 previously) so the incompatibility is gone, and CPU with fullscreen YouTube goes from roughly 170% to 15-30% with H264 1080p 30Hz or 60Hz . I can confirm seeking does not crash now. CAVEAT: 1. the browser is crashing sometimes now when it didn't before but that may due to 2. changes to my about:flags - I haven't isolated yet.

**Comment by hexchain** [comment] 2019-02-28 15:00
The old libva-intel-driver may be in use if it's installed. Could you please verify that you are really using the new media-driver? e.g. run applications (vainfo, chromium) with environment `LIBVA_DRIVER_NAME=iHD` and try to reproduce the problem.

**Comment by widefox** [comment] 2019-02-28 17:31
@hexchain @maximbaz my mistake - you're both right. It still fails with the iHD driver - 1.0.0 . It works with the Intel i965 driver. I must have only had the iHD driver before the 1.3/1.4 issue, but now have both. (This is with ffmpeg version 4.0.3 )

**Comment by enihcam** [comment] 2019-02-28 23:50
@maximbaz @hexchain can you find more details from driver logs instead of chromium logs, and then open a new bug? I don't think they will take a look at this 'chromium issue'. You know what i mean.

By the way, i have switched back to i965 driver already, because I'll get an AMD laptop next month.

**Comment by maximbaz** [comment] 2019-03-01 09:10
unfortunately I have no idea how to do that - could you please help the issue open? many people have already subscribed to it

**Comment by enihcam** [comment] 2019-03-01 09:54
https://01.org/linuxgraphics/documentation/bugs-and-debugging

**Comment by enihcam** [comment] 2019-03-05 16:29
Try replace ffmpeg with ffmpeg-qsv?

**Comment by Spongman** [comment] 2019-04-25 20:04
how do you set an environment variable for a program that's running inside a snap?

**Comment by wangyan-intel** [comment] 2019-08-30 02:43
It should be fixed by https://github.com/intel/media-driver/pull/562. This PR have been merged. Keep this issue one week. If no more response, I will close it.

**Comment by maximbaz** [comment] 2019-08-30 11:37
I can confirm that I no longer reproduce the issue, great work!

**Comment by wangyan-intel** [comment] 2019-09-01 12:26
@maximbaz Thanks for your confirmation.

**Closed by wangyan-intel** 2019-09-01 12:26 UTC
