### ISSUE TITLE
For decoders, vaCreateConfig() returns INVALID_PARAMETER if no attributes supplied.

### ISSUE THREAD

**Issue by djie1** [intel/media-driver#377] opened 2018-10-24 10:57 UTC
For the decoding, if vaCreateConfig() is called with (attrib_list == NULL && num_attribs == 0), it returns INVALID_PARAMETER.

**Comment by uartie** [comment] 2018-10-24 14:32
AFAIK, this is being addressed by @shiqiangyu soon... see patch in #363 and other related regressions caused by this in #372 and #373.

**Comment by djie1** [comment] 2018-10-25 01:53
@uartie , correct, patch in #363 could fix this issue and the encoding related regressions.

**Comment by uartie** [comment] 2018-10-26 19:30
3c55dfe3061e49a3507d50cf60dafe12583b506c reverts the regressing commit. Please reference issue numbers (e.g. #377) in commit messages. GitHub will automatically create link between issue and commit and makes it easier to see when activity occurs for specific issue.

**Closed** 2019-08-29 08:47 UTC
