### ISSUE TITLE
ffmpeg-vaapi decode 10bit vp9 regresstion on TGL

### ISSUE THREAD

**Issue by xinyudox** [intel/media-driver#928] opened 2020-05-06 07:19 UTC
This regression is caused by this patch in media driver.

commit d066e648a1d36862ecedc07d3529f4249ad981de
Author: Chen, Jason K <jason.k.chen@intel.com>
Date:   Sun Apr 26 12:03:07 2020 +0800
 
    [VP] Add condition to use VP in GetImage
    
    Some format like 444P/422V/422H can be supported as input for VP, but cannot be supported as output, thus cannot always use vp to do a conversion in GetImage.

command line:
ffmpeg -hwaccel vaapi -init_hw_device vaapi=hw:/dev/dri/renderD128 -hwaccel_flags allow_profile_mismatch -filter_hw_device hw -v verbose -i ./vp9_PU32x32_NEAREST_10bit_fastfood_64x64.ivf -pix_fmt p010le -f rawvideo -vsync passthrough -vframes 2 -y ./test.yuv

md5:expect = 8eb47bccdc057d8f5b664ce9d64a1335
md5:actual = 06dafcc8fdbbf5ac0aac2b241e420025

**Comment by Jister** [comment] 2020-05-14 06:04
@xinyudox Could you please try the latest media driver to see whether the issue is still there or not?

**Comment by xinyudox** [comment] 2020-05-14 06:27
Hi Jason

There is not this regression in the last report,.

Thanks,
Xinyu

**Comment by Jister** [comment] 2020-05-14 08:15
Thanks. Since the issue is fixed, just close this issue.

**Closed by Jister** 2020-05-14 08:15 UTC
