### ISSUE TITLE
[Bug]: Cannot build on musl

### ISSUE THREAD

**Issue by quentinschibler** [intel/media-driver#1533] opened 2022-10-30 15:16 UTC
### Which component impacted?

Build

### What happened?

Using musl as libc, I am not able to build because execinfo.h is not found.

### What's the usage scenario when you are seeing the problem?

Others

### Debug Information

Here is the output of the build :

media_softlet/linux/common/os/osservice/mos_utilities_specific.cpp:37:10: fatal error: execinfo.h: No such file or directory

### Do you want to contribute a patch to fix the issue?

[Here](https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/intel-media-driver/patches/execinfo.patch) is a patch from void linux. It doesn't work on master, but I'll try to edit it.

**Comment by quentinschibler** [comment] 2022-10-30 16:32
Here is the modified patch, working on master :
[execinfo.txt](https://github.com/intel/media-driver/files/9896301/execinfo.txt)

**Comment by bkuhls** [comment] 2022-10-31 18:19
duplicate of https://github.com/intel/media-driver/pull/1437, had no time to look at FindBacktrace yet

**Comment by dvrogozh** [comment] 2022-10-31 18:55
> Using musl as libc,

@quentinschibler : what is musl? Please, be specific and provide:
1. OS you are working on
2. Additional packages you've installed
3. cmake configuration command line

I guess there is specific way you've installed "musl" and added cmake configuration - that's essential for the bug description.

**Comment by quentinschibler** [comment] 2022-10-31 19:02
> duplicate of #1437, had no time to look at FindBacktrace yet

Sorry, I searched for musl in the issue tracker, and had not found anything. Probably because the issue was using uClibc. You can close the issue then.

**Comment by quentinschibler** [comment] 2022-10-31 19:09
> > Using musl as libc,
> 
> @quentinschibler : what is musl? Please, be specific and provide:
> 
>     1. OS you are working on
> 
>     2. Additional packages you've installed
> 
>     3. cmake configuration command line
> 
> 
> I guess there is specific way you've installed "musl" and added cmake configuration - that's essential for the bug description.

os is linux.
musl is a libc implementation, the installation process is somewhat similar to glibc, and is not relevant to the issue. The issue is that execinfo, which a glibc specific header that is NOT part of the libc specification, is used without checking for glibc in CMakeList.txt.

**Comment by dvrogozh** [comment] 2022-10-31 19:18
> Musl is a libc implementation, the installation process is somewhat similar to glibc, and is not relevant to the issue.

It is relevant. You file an issue to open source project. How issue can be reproduced? That's needed at least to make sure that the provided fix won't be blind and can be verified.

**Comment by quentinschibler** [comment] 2022-10-31 19:26
If you want to reproduce the issue, you'd be better off installing a linux distro using musl. If you absolutely want to install musl on an existing system, then you can follow the "building a cross compiler targeting musl libc" [here](https://wiki.musl-libc.org/getting-started.html).

**Comment by dvrogozh** [comment] 2022-10-31 19:31
This will do. Thank you.

**Closed** 2022-11-16 16:04 UTC
Labels: Build, Common
